name: calculator
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  http: ^0.13.4
  velocity_x: ^3.3.0
  flutter_svg: ^0.22.0 # help us to use SVG in our app
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.2.1+1
  animations: ^2.0.3
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_image_slideshow: ^0.1.6
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  badges: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
#    - assets/files/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

